public class Apex_SObjects {
    
    public static List<SObject> fieldHasChanged(Map<Id,SObject> oldRecords,Map<Id,SObject> newRecords,String fieldApiName){
        return null;
    }
    
    public static List<SObject> fieldHasNewValue(Map<Id,SObject> oldRecords,Map<Id,SObject> newRecords,String fieldApiName,String newValue){
        return null;
    }
    
    public static List<SObject> fieldChangedFromTo(Map<Id,SObject> oldRecords,Map<Id,SObject> newRecords,String fieldApiName,String oldValue,String newValue){
        return null;
    }

}