public class SFMD {
    
        public Enum type {
            DETAIL_BUTTON,
             QUICK_ACTION,PLATFORM_ACTION,
                LAYOUT_SECTION_NAME,
        CUSTOM_FIELD_LABEL,
            CUSTOM_FIELD_HELP_TEXT,
            STANDARD_FIELD_HELP_TEXT,
            STANDARD_PICKLIST_VALUE,
                CUSTOM_PICKLIST_VALUE,
            RELATED_LIST_BUTTON,RELATED_LIST_FIELD,RELATED_LIST_PICKLIST_VALUE        
            }

}